### ISSUE TITLE
would  there be a separate Pricing section or page

### ISSUE THREAD

**Issue by wanghaisheng** [ladunjexa/GitHub-Webpage#1]
https://terrateam.io/#pricing
is an example I likes

**Comment by ladunjexa** [comment]
Hi @wanghaisheng,

When I get around to it, I'll add pages accordingly to GitHub homepage.

In any case, If you're interested in knowing how to implement such blocks in TailwindCSS, you can take a look at TailwindUI, Flowbite or other websites.

[Here](https://tailwindui.com/components/marketing/sections/pricing) you can find something similar to terrateam pricing section.
